name: Fineract Docker build - MariaDB

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Set up JDK 17
        uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3 # tag=v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Build the image
        run: ./gradlew :fineract-provider:clean :fineract-provider:jibDockerBuild -x test
#      - name: Start the stack
#        run: docker-compose up -d
#      - name: Wait for stack to come up
#        run: sleep 60
#      - name: Check health
#        run: curl -f -k --retry 5 --retry-connrefused --connect-timeout 30 --retry-delay 30 https://localhost:8443/fineract-provider/actuator/health
#      - name: Check info
#        run: (( $(curl -f -k --retry 5 --retry-connrefused --connect-timeout 30 --retry-delay 30 https://localhost:8443/fineract-provider/actuator/info | wc --chars) > 100 ))
      - name: Login docker hub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        # 指定login命令登录hub.docker.com，帐号和密码已经在GitHub网页中配置好了
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: tag image
        run: |
          docker tag fineract:latest 0x153/fineract:latest
      - name: push image
        run: |
          docker push 0x153/fineract:latest
      - name: Upload loc as a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: data
          path: ./fineract-provider/build/data
          retention-days: 1